name: Execution Test

on:
  push:
    branches:
      - main
      - development

jobs:
  run-rscript:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'  # Specify the R version you need

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("readr", "arrow", "fs"), repos="https://cloud.r-project.org")'

    - name: Run R script
      run: |
        Rscript parquet_converter.r testdata
