name: Execution Test

on:
  push:
    branches:
      - main
      - development
      - workflow_test

jobs:
  run-rscript:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'  # Specify the R version you need

    - name: Install readr package
      run: |
        Rscript -e 'install.packages("readr", repos="https://cloud.r-project.org")'

    - name: Install arrow package
      run: |
        Rscript -e 'install.packages("arrow", repos="https://cloud.r-project.org")'

    - name: Install fs package
      run: |
        Rscript -e 'install.packages("fs", repos="https://cloud.r-project.org")'

    - name: Run R script
      run: |
        Rscript parquet_converter.r testdata

    - name: List files in testdata folder
      run: |
        ls testdata
